# Generated by Django 4.2.3 on 2023-07-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_userprofile_qr_image_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_doc',
            field=models.URLField(default=''),
        ),
    ]
