# Generated by Django 4.2.3 on 2023-07-18 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ams", "0004_userprofile_identity_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punchin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
