# Generated by Django 4.2.3 on 2023-07-23 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchin',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
