# Generated by Django 4.2.3 on 2023-07-25 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0010_alter_punchin_checkin_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punchout_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
