# Generated by Django 4.2.3 on 2023-08-02 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0020_alter_punchin_checkin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchin',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 7, 58, 28, 713371, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='punchout',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 7, 58, 28, 713890, tzinfo=datetime.timezone.utc)),
        ),
    ]
